### PR TITLE
Fix ledgers view

### LINKED ISSUE #609: Show discounted price information on admin member charges

### LINKED ISSUE #639: Fix ledger views by always showing general cash ledger

### PR DESCRIPTION
**Pull request by DeeTheDev**
Fixes #639 Fixes #609 

Recently we changed the ledgers view by removing ledgers without any transactions. We must always return the general 'cash' ledger when it is available. Fix the `LedgersOverview` to fully support 'no ledgers available'.

Screenshot 2024-05-06 at 11 02 14 AM

---

Show/expose discounted price in the adminapp's member charge details.

Screenshot 2024-05-05 at 3 20 59 PM

### CODE REVIEW

File: spec/suma/api/ledgers_spec.rb [hunk 1]
```diff
@@ -7,31 +7,32 @@
   include Rack::Test::Methods
 
   let(:app) { described_class.build_app }
-  let(:member) { Suma::Fixtures.member.create }
+  let(:member) { Suma::Fixtures.member.with_cash_ledger.create }
```
Comment (rgalanakis) [inline spec/suma/api/ledgers_spec.rb:10]: What if there is no cash ledger? You added a precondition to how your code functions (cash ledger must exist) but don't test what happens if that condition is not met.

**Review by rgalanakis — CHANGES_REQUESTED** [review]

File: lib/suma/api/ledgers.rb [hunk 2]
```diff
@@ -7,10 +7,10 @@ class Suma::API::Ledgers < Suma::API::V1
   include Suma::API::Entities
 
   resource :ledgers do
-    desc "Return an overview of all ledgers including balances, and recent transactions."
+    desc "Return an overview of cash ledger and ledgers with transactions including balances, and recent transactions."
     get :overview do
       me = current_member
-      ledgers = (me.payment_account&.ledgers || []).select(&:any_transactions?)
+      ledgers = (me.payment_account&.ledgers || []).select { |led| led.any_transactions? || led.name === "Cash" }
```
Comment (rgalanakis) [inline lib/suma/api/ledgers.rb:13]: This should be `led.slug == "cash"` as per
```
  one_to_one :cash_ledger, class: "Suma::Payment::Ledger", read_only: true do |ds|
    ds.where(vendor_service_categories: Suma::Vendor::ServiceCategory.where(slug: "cash"))
  end
  ```

File: webapp/public/locale/en/strings.json [hunk 3]
```diff
@@ -314,6 +314,7 @@
     "linked_bank_account_successful": "Your bank account has been successfully linked to Suma. Within the next day or two, one of our Member Experience specialists will be in touch to confirm the account.\n\nOnce the account is confirmed, you'll be able to add funds.",
     "no_bank_accounts_warning": "You don't have any bank accounts linked.",
     "no_cards_warning": "You don't have any credit or debit cards linked.",
+    "no_ledgers_warning": "You don't have any payment ledgers.",
```
Comment (rgalanakis) [inline webapp/public/locale/en/strings.json:317]: This is not a useful warning or anything anyone can do anything about. Show the generic error message- something went wrong on suma's side and the user doesn't really care what it is.

**Review by rgalanakis — CHANGES_REQUESTED** [review]

File: webapp/public/locale/en/strings.json (hunk 3 above)
Comment (DeeTheDev) [reply webapp/public/locale/en/strings.json]: Okay let me know if this works better:
Screenshot 2024-05-06 at 1 02 17 PM

File: webapp/src/pages/LedgersOverview.jsx [hunk 4]
```diff
@@ -110,7 +113,9 @@ export default function LedgersOverview() {
           />
         </>
       ) : (
-        <PageLoader buffered />
+        <p className="text-center mx-3 text-danger">
+          {t("errors:something_went_wrong_title")}
```
Comment (rgalanakis) [inline webapp/src/pages/LedgersOverview.jsx:117]: This is why we have the `ErrorScreen` component, use it please.

File: webapp/src/pages/LedgersOverview.jsx [hunk 5]
```diff
@@ -89,34 +90,33 @@ export default function LedgersOverview() {
   if (ledgersOverviewLoading && ledgerLinesFetch) {
     return <PageLoader buffered />;
   }
+  if (!isEmpty(ledgersOverview.ledgers)) {
```
[the remark this answers is not in the document]
Comment (DeeTheDev) [reply webapp/src/pages/LedgersOverview.jsx]: I had tested it, forgot to remove the bang, thanks. @rgalanakis Pushed the commit.
