### PR TITLE
Ignore 404 twilio verification errors

### LINKED ISSUE #711: Ignore twilio verification for expired/invalid reset codes
Twilio expires their codes after 10 minutes if the verification lifecycle wasn't completed (Code created -> Accepted/Canceled). Twilio is failing with an [HTTP error](https://lithic-technology.sentry.io/issues/5880814468/?alert_rule_id=12147465&alert_type=issue&notification_uuid=aab09819-b1c1-4b35-8d36-dd8d1472c069&project=6724127&referrer=slack) when a reset code was created but wasn't used for longer than 10 min. We need to ignore this HTTP error since twilio has already expired the code - ending it's verification cycle.

### PR DESCRIPTION
**Pull request by DeeTheDev**
Fixes #711 

Twilio's verification updates have 404 HTTP errors that mean that a code has been approved, expired or invalidated (for security measures). This error should be ignored since twilio handles the reset code, and suma expires after 15 min.

### CODE REVIEW

File: lib/suma/async/reset_code_update_twilio.rb [hunk 1]
```diff
@@ -30,6 +30,12 @@ def update_verification(code, status)
         # the 'send via twilio verify' logic in SmsTransport, so we only update twilio when we use that template.
         Suma::Message::SmsTransport.verification_delivery?(md)
     verification_id = Suma::Message::SmsTransport.transport_message_id_to_verification_id(md.transport_message_id)
-    Suma::Twilio.update_verification(verification_id, status:)
+    begin
+      Suma::Twilio.update_verification(verification_id, status:)
+    rescue Twilio::REST::RestError => e
+      # 404 means twilio has approved, expired or invalidated the code already
+      # https://www.twilio.com/docs/verify/api/verification-check#check-a-verification
+      nil if e.code === 404
```
Comment (rgalanakis) [inline lib/suma/async/reset_code_update_twilio.rb:38]: You're not re-raising if the code is *not* a 404.
Also can you explain why this is in the job, and not `update_verification`?

Comment (DeeTheDev) [reply lib/suma/async/reset_code_update_twilio.rb]: Good catch. And I overlooked that the `update_verification` method calls the actual client to make the request, thanks I moved it into the method.

File: spec/suma/async/jobs_spec.rb [hunk 2]
```diff
@@ -206,6 +206,32 @@
       end.to perform_async_job(Suma::Async::ResetCodeUpdateTwilio)
     end
 
+    it "ignores twilio 404s for invalid, expired or approved reset codes" do
```
Comment (rgalanakis) [inline spec/suma/async/jobs_spec.rb:209]: These should be tested in `twilio_spec`, not the job.

Comment (DeeTheDev) [reply spec/suma/async/jobs_spec.rb]: Thanks, I had suspicion, they're moved now
