### PR TITLE
Update restricted mobility warning and fix bug

### LINKED ISSUE #586: Fix mobility restricted warnings
When we restrict mobility, we should update the warning to say something like:
> “Thanks for your interest! Mobility options are currently in the works and we’ll announce when they’re available”
- [ ] Adding something like “email us at apphelp@mysuma.org if you’re interested in helping us test our upcoming mobility options”

When this warning popup appears, it is also followed by a "Add funds" button, which should not be present:
- [ ] removing the “add funds” button from the pop up box

### PR DESCRIPTION
**Pull request by DeeTheDev**
Fixes #586 

- Update restricted mobility popup warning when vehicle is clicked
- Remove "Add Funds" button if mobility is restricted

### Updated mobility warning
Screenshot 2024-01-18 at 4 55 58 PM

### CODE REVIEW

File: webapp/src/components/mobilitymap/Map.jsx [hunk 1]
```diff
@@ -183,13 +184,14 @@ export default function Map() {
...
         <CardOverlay>
           <FormError error={error} noMargin component="div" />
-          {readOnlyReason(user, "read_only_zero_balance") && (
-            <div className="text-center mt-2">
-              <Button variant="outline-success" to="/funding" size="sm" as={RLink}>
-                {t("payments:add_funds")}
-              </Button>
-            </div>
-          )}
+          {isUndefined(config.featureMobilityRestricted) &&
```
Comment (rgalanakis) [inline webapp/src/components/mobilitymap/Map.jsx:187]: `!config.featureMobilityRestricted`. It may be an empty string if set but empty.
