### PR TITLE
Fix ledgers pagination layout

### LINKED ISSUE #701: Fix ledger view loading image overlapping pagination buttons
It should not be overlapping, specially with a position absolute property. Possible solution is to add a high z-index property on the loader.

Screenshot 2024-09-10 at 8 56 29 PM

### PR DESCRIPTION
**Pull request by DeeTheDev**
Fixes #701 

Remove pagination if there are no lines. Also, since an empty space looks weird, add a 'no transactions' message.

Screenshot 2024-09-16 at 4 34 32 PM

### CODE REVIEW

File: webapp/src/pages/LedgersOverview.jsx [hunk 1]
```diff
@@ -109,12 +109,16 @@ export default function LedgersOverview() {
...
-            />
+            {!isEmpty(activeLines) ? (
+              <ForwardBackPagination
+                page={page}
+                pageCount={ledgerLines.pageCount}
+                onPageChange={(pg) => setListQueryParams({ page: pg })}
+                scrollTop={140}
+              />
+            ) : (
+              <p className="text-center">{t("payments:no_transaction_history")}</p>
```
Comment (rgalanakis) [inline webapp/src/pages/LedgersOverview.jsx:120]: This isn't true, so is confusing- they can be looking at an empty ledger but have spent money elsewhere. Either rephrase or remove.
