### PR TITLE
Fix GBFS bike battery level validation error

### LINKED ISSUE #512: Fix GBFS bike battery level validation error
staging caught the battery level over the constraint max (100). We can ensure the battery_level max and min are valid with the `clamp` method

### PR DESCRIPTION
**Pull request by DeeTheDev**
Fixes #512

- Use the `clamp` method to validate the battery level constraints (> 0, < 100) on the fetched GBFS bikes.

### CODE REVIEW

File: lib/suma/mobility/gbfs/free_bike_status.rb [hunk 1]
```diff
@@ -19,7 +19,7 @@ def yield_rows(vendor_service)
       next unless (vehicle_type = vehicle_types_by_id[bike["vehicle_type_id"]])
       battery_level = nil
       if (current_range = bike["current_range_meters"]) && (max_range = vehicle_type["max_range_meters"])
-        battery_level = ((current_range.to_f / max_range) * 100).round
+        battery_level = ((current_range.to_f / max_range) * 100).round.clamp(0, 100)
```
Comment (rgalanakis) [inline lib/suma/mobility/gbfs/free_bike_status.rb:22]: Needs a test
