### PR TITLE
Fix area restrictions bug

### LINKED ISSUE #386: Find geofencing zones closest point of surface from centroid
Geofencing zone center is not calculated correctly since some label markers appear outside of the surface of the zone area. 

We should find a way to get the closest "point of surface" from the centroid (backend work is a possibility). 
Then we should use this point in the frontend map to adjust the label markers lat, lng coordinates.

Screenshot 2023-04-11 at 3 55 28 PM

### LINKED ISSUE #491: Improve map restriction UI
Problem: the center popup for each restriction area is not centered correctly (missing centroid formula).

To avoid this issue, we can just remove this center marker and when clicking on the area surface, then popup will appear with restriction details.

### LINKED ISSUE #493: Fix bug where map restrictions have null values
When we load restrictions, if there is a null value for that restriction (e.g. "do-not-park"), the function will stop rendering the rest of the markers on the map. This is why we don't see half of the restrictions on the map.

In the backend, we need ensure that creating a Suma::Mobility::RestrictedArea does not return any null values.
At the moment, we are returning a null value for the "restriction" property.

We need to:

- Double check specs for the GBFS to check what types of restrictions should be applied for the specific rules
- Add migration to make restriction values `null: false` or not_nullable
- Should likely add more tests

- UI: we should add a condition to skip creating any markers if it has null values - we want to avoid as many rendering errors or mishaps as possible

### PR DESCRIPTION
**Pull request by DeeTheDev**
Fixes #491 fixes #386 (by getting rid of centroid) fixes #493

* Create migration to ensure mobilty area `restriction` column are not nullable
* When fetching mobility areas, limit to those who have a determined restriction, otherwise omit
* UI map restriction areas are conditionally rendered to avoid any rendering bugs

---

- UI map Restriction area popups appears where it was clicked, instead of in a centered marker

### Refactored restriction area popup
Screenshot 2023-08-28 at 6 15 04 PM

### CODE REVIEW

File: db/migrations/034_restricted_mobility_area_not_nullable.rb [hunk 1]
```diff
@@ -0,0 +1,9 @@
+# frozen_string_literal: true
+
+Sequel.migration do
+  change do
+    alter_table(:mobility_restricted_areas) do
+      set_column_not_null :restriction
```
Comment (rgalanakis) [inline db/migrations/034_restricted_mobility_area_not_nullable.rb:6]: What about current restrictions that have a null value?

File: lib/suma/mobility/gbfs/geofencing_zone.rb [hunk 2]
```diff
@@ -24,10 +24,11 @@ def yield_rows(vendor_service)
                         "do-not-park-or-ride"
         elsif rule["ride_allowed"] == false
           "do-not-park"
-          elsif rule["ride_through_allowed"] == false
-            "do-not-ride"
+        elsif rule["ride_through_allowed"] == false
+          "do-not-ride"
         end
       end
+      next if restriction.nil?
```
Comment (rgalanakis) [inline lib/suma/mobility/gbfs/geofencing_zone.rb:31]: So we throw away the restriction if it's not handled? Isn't that a big problem?
