### PR TITLE
Add Spanish locale file and layout fixes

### LINKED ISSUE #90: Integrate translations

### PR DESCRIPTION
**Pull request by DeeTheDev**
Fixes #90 
- Import Spanish translation in locales files (and adjust translation accordingly)
- Finish translation in navbar & other areas
- Change Logout button color to "danger"
- Add initial amount for Numpad in **Add Funds** page
- Widen Map card layout (Spanish translations have lengthy text)

Note:
- Translations missing only in some `alt` tags and in the maps' Enable Location Services instructions modal

### CODE REVIEW

File: webapp/src/pages/Start.js [hunk 1]
```diff
@@ -58,7 +58,7 @@ export default function Start() {
   return (
     <>
       <h2>{t("forms:get_started")}</h2>
-      <p>{t("forms:get_started_intro")}</p>
+      <p id="phoneRequired">{t("forms:get_started_intro")}</p>
```
Comment (DeeTheDev) [inline webapp/src/pages/Start.js:61]: This `id` links to the `area-describedby` in the phone input field
