### PR TITLE
Add funds validation, pages template and fix spacing

### LINKED ISSUE #111: Do not make map requests when the map is not loaded

### LINKED ISSUE #126: Add validation to FundingLinkBankAccount page
- [ ] **[Dee]** Checking/savings radio elements need `id` property to be recognized by their labels.

### LINKED ISSUE #131: Clean up layouts
Right now we have a few issues with layouts.

The main one is, we use `div>Row>Col`. Anytime we use a Row, it MUST be nested in a container. Otherwise we get weird gutters.

You can repro the layout issues on a small screen- instead of sitting flush, the layout renders past the edges, allowing horizontal scrolling. Using the correct Bootstrap nesting should solve this problem.

### PR DESCRIPTION
**Pull request by DeeTheDev**
Fixes #131
- Clean up layout spacing and gutter issues within every page and table
- Added page layout template `withLayout`
- Fix subtle translation issues #
<hr>
Fixes #126  

- Add React-Form validation to "Funding link bank account" page
<hr>
Fixes #111 

- Stop map api refresh when map is unmounted

### CODE REVIEW

File: webapp/src/components/mobilitymap/Map.js [hunk 1]
```diff
@@ -115,6 +115,11 @@ const Map = () => {
       }
       setLoadedMap(map);
     }
+    return () => {
+      if (loadedMap) {
+        loadedMap.tripMode();
```
Comment (DeeTheDev) [inline webapp/src/components/mobilitymap/Map.js:120]: This method stops all map event handlers and refresh timer.
