### PR TITLE
Fix checkout bugs

### LINKED ISSUE #573: If a member has ordered more than the max allowed, it looks like they can order more
- Set a limit of 5 item per member per offering
- Purchase 5 of a thing
- Set the limit to 1
- It allows you to add more to the cart, but it should not

### LINKED ISSUE #574: All products should be sold out if an offering is closed
If offering 5 is closed, you can still reach it at `/app/food/5`. That is fine; but there should not let you try to purchase it. Make sure creating the checkout errors as well, and trying to complete an order does too.

### PR DESCRIPTION
**Pull request by DeeTheDev**
Fixes #574 
Fixes #573 

- Fix bug where out_of_stock was conditioned to equals zero, but should be zero or less
- Fix bug where offering is reachable after it is closed, and we allowed members to purchase based on the inventory available, fixed by setting items as out_of_stock when offering is closed
- Disallow creating a checkout when one or more items are out_of_stock in an offering cart
- Test

---

- Fix lingering Container layout issues where Row was included but unnecessary
- Fix lingering link to button refactors
- Fix markdown usage where unnecessary
- Remove/update localizations where necessary

### Offering cart page disallows continuing to checkout based on item quantity
Screenshot 2023-12-13 at 8 12 56 PM

### Layout and link refactors
Screenshot 2023-12-13 at 8 04 43 PM

Screenshot 2023-12-13 at 8 05 13 PM

Screenshot 2023-12-13 at 8 15 08 PM

### CODE REVIEW

File: lib/suma/api/commerce.rb [hunk 1]
```diff
@@ -251,7 +254,7 @@ class OfferingProductEntity < BaseEntity
 
     expose :max_quantity
     expose :out_of_stock do |_|
```
Comment (rgalanakis) [inline lib/suma/api/commerce.rb:256]: Move this to the model, and test it explicitly.

File: lib/suma/commerce/cart.rb [hunk 2]
```diff
@@ -101,11 +101,13 @@ def set_item(product, quantity, timestamp:)
 
   # This seems like a reasonable default...
   DEFAULT_MAX_QUANTITY = 12
+  CLOSED_OFFERING_MAX_QUANTITY = 0
 
   def max_quantity_for(offering_product)
     product = offering_product.product
     inv = product.inventory!
     offering = offering_product.offering
+    return CLOSED_OFFERING_MAX_QUANTITY unless offering.available_at?(Time.now)
```
Comment (rgalanakis) [inline lib/suma/commerce/cart.rb:110]: There's a reason we don't use `Time.now` like this elsewhere. It needs to be passed in.

Also I would not put this here. You're mixing two ideas- actual quantity, and availability of an offering. Imagine you had the ability for admins to order a thing, irrespective of whether the offering is closed. The quantity still needs to be accurate.

Instead look at line 81 in `api/commerce.rb`. There's already an `available?` predicate which represents a similar concept, and can be used.

File: lib/suma/commerce/cart.rb [hunk 3]
```diff
@@ -101,11 +101,13 @@ def set_item(product, quantity, timestamp:)
 
   # This seems like a reasonable default...
   DEFAULT_MAX_QUANTITY = 12
+  CLOSED_OFFERING_MAX_QUANTITY = 0
```
Comment (rgalanakis) [inline lib/suma/commerce/cart.rb:104]: This isn't helpful as a constant. What other value could it be?

File: lib/suma/fixtures/offerings.rb [hunk 4]
```diff
@@ -46,4 +46,9 @@ module Suma::Fixtures::Offerings
   decorator :with_constraints, presave: true do |*constraints|
     constraints.each { |c| self.add_eligibility_constraint(c) }
   end
+
+  decorator :max_cumulative_and_per_member do |max_cumulative, max_per_member|
```
Comment (rgalanakis) [inline lib/suma/fixtures/offerings.rb:50]: This is a confusing decorator. There's no dependency between these two fields. Remove it.

**Review by rgalanakis — CHANGES_REQUESTED** [review]

File: lib/suma/api/commerce.rb (hunk 1 above)
Comment (DeeTheDev) [reply lib/suma/api/commerce.rb:256]: @rgalanakis `out_of_stock` is reliant on the member's cart. How would this `out_of_stock` method fetch the necessary member? I haven't figured it out yet.

Comment (rgalanakis) [reply lib/suma/api/commerce.rb:256]: Ah, I see. Ok, that's fine- this would be a pain to modify, either resulting in additional calculations, or a lot more complexity. Add a test though.

Comment (rgalanakis) [reply lib/suma/api/commerce.rb:256]: FWIW, I would model `max_quantity_for` to `quantity_info_for` and return an object with fields like `max_quantity` and `out_of_stock`, rather than returning an integer. But I don't think that change is worth it for now.

Comment (DeeTheDev) [reply lib/suma/api/commerce.rb:256]: I agree it would add complexity. I'll go ahead and add tests for this.

File: lib/suma/commerce/cart_item.rb [hunk 5]
```diff
@@ -35,8 +35,10 @@ class Suma::Commerce::CartItem < Suma::Postgres::Model(:commerce_cart_items)
       where(offering_id: self.cart.offering_id, product_id: self.product_id)
   end
 
-  def available?
-    return self.offering_product&.available? || false
+  def available_at?(now: Time.now)
```
Comment (rgalanakis) [inline lib/suma/commerce/cart_item.rb:38]: Get rid of the default.

File: lib/suma/commerce/cart_item.rb [hunk 6]
```diff
@@ -35,8 +35,10 @@ class Suma::Commerce::CartItem < Suma::Postgres::Model(:commerce_cart_items)
...
+    return false if self.offering_product.nil?
+    return false if self.offering_product.offering.period_end < now
+    return self.offering_product&.available?
```
Comment (rgalanakis) [inline lib/suma/commerce/cart_item.rb:41]: What's the point of the `&` here?

File: lib/suma/commerce/cart_item.rb [hunk 7]
```diff
@@ -35,8 +35,10 @@ class Suma::Commerce::CartItem < Suma::Postgres::Model(:commerce_cart_items)
       where(offering_id: self.cart.offering_id, product_id: self.product_id)
   end
 
-  def available?
-    return self.offering_product&.available? || false
+  def available_at?(now: Time.now)
+    return false if self.offering_product.nil?
+    return false if self.offering_product.offering.period_end < now
```
Comment (rgalanakis) [inline lib/suma/commerce/cart_item.rb:40]: This would mean something is available before the offering is open.

File: lib/suma/commerce/checkout.rb [hunk 8]
```diff
@@ -113,7 +113,8 @@ def requires_payment_instrument?
     return self.chargeable_amount?
   end
 
-  def checkout_prohibited_reason
+  def checkout_prohibited_reason(now: Time.now)
```
Comment (rgalanakis) [inline lib/suma/commerce/checkout.rb:116]: Get rid of the default

Comment (rgalanakis) [reply lib/suma/commerce/checkout.rb:116]: As a rule, don't default to an external dependency like `Time.now` in the models unless it makes something much much simpler.

**Review by rgalanakis — CHANGES_REQUESTED** [review]

File: lib/suma/commerce/checkout.rb (hunk 8 above)
Comment (DeeTheDev) [reply lib/suma/commerce/checkout.rb:116]: @rgalanakis For some reason `Grape::Middleware::Formatter` is complaining. I tried to diagnose this but I'm not sure what's happening. Errors when removing a default value:

Screenshot 2023-12-15 at 9 50 34 AM
